envs:
 global:
    variables:
      TAPIR: "%{credentials.secret('tapir')}"
      AARDVARK: "$aardvark"
flows:
  master:
    - env
    - cat /tmp/*.sh
    - (name echo build_number) echo "BUILD_NUMBER" ${BUILD_NUMBER}
    - (name echo to file) echo "Secret value of tapir is:" ${TAPIR} > tapir.txt
    - (name echo secret) echo "Secret value of tapir is:" $TAPIR
    - (name echo injected to file) echo "Secret value of tapir is:" ${AARDVARK} > tapir.txt
    - (name echo injected secret) echo "Secret value of tapir is:" $AARDVARK
