flows:
  master:
    - (on master, name master-node) uname -a > master.txt
    - (on osx, name osx-node) uname -a > osx.txt
    - (on linux, name linux-node) uname -a > linux.txt
    - call: build

  build:
    (on master-node):
      - uname -a
      - ls -la
