flows:
  master:
    - env
    - (name echo build_number) echo "BUILD_NUMBER: $BUILD_NUMBER"
    - (name echo to file) echo "Secret value of tapir is: $tapir" > tapir.txt
    - (name echo secret) echo "Secret value of tapir is: $tapir"
