flows:
  master:
    - uname -a > master.txt
    - (on osx, name osx-node) uname -a > osx.txt
    - (on linux, name linux-node) uname -a > linux.txt
    - call: build

  build:
    - (on linux):
      - uname -a
      - ls -la
      - call: linux-task
    - (on osx):
      - uname -a
      - ls -la

  linux-task:
    (on linux) ls -la
