flows:
  master:
    - call: build
    - ws_snapshot: snap
    - call: test_ios
    - call: test_android

  build:
    - (on osx) touch wname.txt
    - (on osx) shell: uname -a > uname.txt

  test_ios:
    (on osx):
      - ws_restore: snap
      - uname -a
      - ls -l wname.txt
      - cat uname.txt


  test_android:
    (on master):
      - ws_restore: snap
      - uname -a
      - ls -l wname.txt
      - cat uname.txt
