envs:
 global:
    variables:
      SSH_KEY: "%{credentials.secret('a_ssh')}"
      SSH_FILE: "%{credentials.filename('a_ssh')}"
      GIT_SSH_COMMAND: "ssh -i %{credentials.filename('a_ssh')}"

flows:
  master:
    - env
    - (name echo build_number) echo "BUILD_NUMBER" ${BUILD_NUMBER}
    - echo "$SSH_KEY" "$SSH_FILE"
    - git clone git@gecgithub01.walmart.com:Walmart-Android/walmart-android.git
