flows:
  master:
    - call: build
    - call: test_ios
    - call: test_android

  build:
    (on osx):
      - touch uname.txt
      - shell: "uname -a > uname.txt"
      # - ws_snapshot: snap

  test_ios:
    (on osx):
      # - ws_restore: snap
      - uname -a
      - cat uname.txt


  test_android:
    (on master):
      # - ws_restore: snap
      - uname -a
      - cat uname.txt
