flows:
  master:
    - call: build
    - call: test_android
    - call: test_ios

  build:
    (on osx):
      - shell: "uname -a > uname.txt"
      - sleep 10
      - ws_snapshot: snap

  test_ios:
    (on osx):
      - ws_restore: snap
      - uname -a
      - cat uname.txt
      - sleep 10


  test_android:
    (on master):
      - ws_restore: snap
      - uname -a
      - cat uname.txt
      - sleep 10
