flows:
  master:
    - uname -a > master.txt; chmod a+x master.txt
    - (on osx, name osx-node) uname -a > osx.txt; chmod a+x osx.txt
    - (on linux, name linux-node) uname -a > linux.txt; chmod a+x linux.txt
    - call: build

  build:
    - (on linux):
      - uname -a
      - ls -la
    - (on osx):
      - uname -a
      - ls -la

